#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"

ROOT = File.expand_path("..", __dir__)
SOURCE_DIR = File.join(ROOT, "agents")
CLAUDE_DIR = File.join(ROOT, ".claude", "agents")
CODEX_DIR = File.join(ROOT, ".codex", "agents")

CLAUDE_ONLY = ["kyle"].freeze
CODEX_ONLY = ["randy"].freeze
NON_AGENTS = %w[README CHANGELOG DECISION_ROUTING debra-knowledge nell-knowledge].freeze

def parse_agent(path)
  text = File.read(path)
  match = text.match(/\A---\n(?<frontmatter>.*?)\n---\n(?<body>.*)\z/m)
  raise "Missing YAML frontmatter: #{path}" unless match

  fields = match[:frontmatter].lines.map do |line|
    key, value = line.chomp.split(":", 2)
    [key, value.strip] if value
  end.compact.to_h

  name = fields.fetch("name").downcase.tr(" ", "-")
  description = fields.fetch("description")
  [name, description, match[:body]]
end

def toml_string(value)
  value.dump
end

FileUtils.mkdir_p(CLAUDE_DIR)
FileUtils.mkdir_p(CODEX_DIR)

agent_paths = Dir[File.join(SOURCE_DIR, "*.md")].reject do |path|
  NON_AGENTS.include?(File.basename(path, ".md"))
end

agents = agent_paths.map { |path| [path, *parse_agent(path)] }
names = agents.map { |_, name, _, _| name }

requested_file, requested_ai = ARGV
if ARGV.length == 1 || ARGV.length > 2
  abort "Usage: #{File.basename($PROGRAM_NAME)} [agent.md claude|codex|all]"
end

targeted = !requested_file.nil?
if targeted
  requested_ai = requested_ai.downcase
  abort "AI must be claude, codex, or all" unless %w[claude codex all].include?(requested_ai)

  requested_name = File.basename(requested_file).sub(/\.md\z/i, "").downcase.tr(" ", "-")
  selected = agents.select { |_, name, _, _| name == requested_name }
  abort "Agent not found in #{SOURCE_DIR}: #{requested_file}" if selected.empty?
  abort "#{requested_name} is Claude-only; update CLAUDE_ONLY before targeting Codex" if CLAUDE_ONLY.include?(requested_name) && %w[codex all].include?(requested_ai)
  abort "#{requested_name} is Codex-only; update CODEX_ONLY before targeting Claude" if CODEX_ONLY.include?(requested_name) && %w[claude all].include?(requested_ai)
  agents = selected
end

unless targeted
  Dir[File.join(CLAUDE_DIR, "*.md")].each do |path|
    FileUtils.rm_f(path) unless (names - CODEX_ONLY).include?(File.basename(path, ".md"))
  end
  Dir[File.join(CODEX_DIR, "*.toml")].each do |path|
    FileUtils.rm_f(path) unless (names - CLAUDE_ONLY).include?(File.basename(path, ".toml"))
  end
end

agents.each do |source, name, description, body|
  sync_claude = !CODEX_ONLY.include?(name) && (!targeted || %w[claude all].include?(requested_ai))
  sync_codex = !CLAUDE_ONLY.include?(name) && (!targeted || %w[codex all].include?(requested_ai))

  if sync_claude
    target = File.join(CLAUDE_DIR, "#{name}.md")
    FileUtils.rm_f(target)
    FileUtils.ln_s(File.join("..", "..", "agents", File.basename(source)), target)
  end

  next unless sync_codex

  instructions = <<~INSTRUCTIONS
    You are the #{name} agent in the AI-Wonder-Team.

    Your canonical agent instructions follow. Paths referenced relative to the agent file resolve from #{SOURCE_DIR}.

    #{body.rstrip}
  INSTRUCTIONS

  toml = <<~TOML
    # Generated by agents/sync-agent-configs.rb from agents/#{File.basename(source)}.
    # Edit the canonical Markdown file, then rerun the sync utility.
    name = #{toml_string(name)}
    description = #{toml_string(description)}
    developer_instructions = #{toml_string(instructions)}
  TOML
  File.write(File.join(CODEX_DIR, "#{name}.toml"), toml)
end

if targeted
  puts "Synced #{agents.first[1]} for #{requested_ai}."
else
  puts "Synced #{agents.length - CODEX_ONLY.length} Claude agents and #{agents.length - CLAUDE_ONLY.length} Codex agents."
end
